---
- name: Install MySQL Packages
  apt:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  loop: 
    - "mysql-server-{{ mysql_major_version }}"
    - "python3-pymysql"
  tags: [ system ]

- name: Check if root password is already set
  command: mysqladmin -uroot -p{{ mysql_root_password }} ping
  register: root_password_set
  failed_when: false
  ignore_errors: true

 # MySQL Configuration
- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: root_password_set.rc != 0
  tags: [ mysql ]

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]
